In [1]:
!pip install --upgrade gspread
# !pip install hvplot
!pip install mlxtend
!pip install -U plotly

import numpy as np
import pandas as pd
import hvplot.pandas
import plotly.express as px
import matplotlib.pyplot as plt

Requirement already up-to-date: gspread in /usr/local/lib/python3.8/dist-packages (5.7.1)
Requirement already satisfied, skipping upgrade: google-auth>=1.12.0 in /usr/local/lib/python3.8/dist-packages (from gspread) (2.14.1)
Requirement already satisfied, skipping upgrade: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from gspread) (0.7.1)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/lib/python3/dist-packages (from google-auth>=1.12.0->gspread) (1.14.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth>=1.12.0->gspread) (0.2.8)
Requirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= "3.6" in /usr/local/lib/python3.8/dist-packages (from google-auth>=1.12.0->gspread) (4.9)
Requirement already satisfied, skipping upgrade: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth>=1.12.0->gspread) (5.2.0)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (1.3.1)
Requirement already satisfied, skipping upgrade: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.28.1)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.2.2)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2019.11.28)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (1.26.13)
Requirement already satisfied, skipping upgrade: charset-normalizer<3,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.1.1)
Requirement already satisfied, skipping upgrade: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.8)
Requirement already satisfied: mlxtend in /usr/local/lib/python3.8/dist-packages (0.21.0)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from mlxtend) (3.6.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.8/dist-packages (from mlxtend) (1.5.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.8/dist-packages (from mlxtend) (1.9.3)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.8/dist-packages (from mlxtend) (1.2.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from mlxtend) (45.2.0)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.8/dist-packages (from mlxtend) (1.1.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.8/dist-packages (from mlxtend) (1.23.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.0.6)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.38.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.0.0->mlxtend) (9.3.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.24.2->mlxtend) (2022.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=1.0.2->mlxtend) (3.1.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.14.0)
Requirement already up-to-date: plotly in /usr/local/lib/python3.8/dist-packages (5.11.0)
Requirement already satisfied, skipping upgrade: tenacity>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from plotly) (8.1.0)

ModuleNotFoundError: No module named 'hvplot'

In [2]:
import scipy.stats
import numpy as np
import matplotlib.pyplot as plt
import functools
import scipy.stats
import pandas as pd
import mlxtend
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
df=pd.read_csv('/workspaces/forPicaiDocker/associationMinusPrep.csv')
df

,Unnamed: 0,Amygdala (AAL) (R),Angular gyrus (AAL) (L),Angular gyrus (AAL) (R),Anterior cingulate and paracingulate gyri (AAL) (L),Anterior cingulate and paracingulate gyri (AAL) (R),Calcarine fissure and surrounding cortex (AAL) (L),Calcarine fissure and surrounding cortex (AAL) (R),Caudate nucleus (AAL) (L),Caudate nucleus (AAL) (R),...,Thalamus (AAL) (L),Thalamus (AAL) (R),Vermis_10 (AAL),Vermis_1_2 (AAL),Vermis_3 (AAL),Vermis_4_5 (AAL),Vermis_6 (AAL),Vermis_7 (AAL),Vermis_8 (AAL),Vermis_9 (AAL)
0,0,0,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,0
1,1,0,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,2,0,True,True,True,True,True,True,True,True,...,0,0,True,0,True,True,True,0,0,0
3,3,0,True,True,True,True,True,True,True,True,...,0,True,True,0,True,True,True,True,True,True
4,4,0,True,True,True,True,True,True,True,True,...,True,True,True,0,True,True,True,True,True,True
5,5,0,True,True,True,True,True,True,True,True,...,0,True,True,True,True,True,True,True,True,0
6,6,0,True,True,True,True,True,True,True,True,...,0,0,True,True,True,True,True,True,0,0
7,7,0,True,True,True,True,True,True,0,True,...,0,0,True,0,0,True,True,0,0,0
8,8,0,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,0,0,0
9,9,True,True,True,True,True,True,True,True,True,...,True,True,True,0,True,True,True,True,True,True
10,10,0,True,True,True,True,True,True,True,True,...,0,0,True,True,True,True,True,True,True,True
11,11,0,True,True,True,True,True,True,True,True,...,0,0,True,0,0,True,True,0,0,0
12,12,0,True,True,True,True,True,True,0,True,...,0,0,True,True,True,True,True,True,0,0
13,13,0,True,True,0,True,True,True,0,True,...,0,0,True,0,0,0,True,True,0,0
14,14,0,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
15,15,0,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,16,0,True,True,0,0,True,True,0,0,...,0,0,True,True,True,True,True,0,0,0
17,17,0,True,True,True,True,True,True,True,True,...,0,0,True,True,True,True,True,True,True,True
18,18,0,True,True,True,True,True,True,True,True,...,True,True,True,0,True,True,True,True,True,0
19,19,0,True,True,True,True,True,True,0,True,...,True,True,True,0,True,True,True,True,0,0

In [9]:
df=df.loc[:, df.columns != 'Unnamed: 0']
df = df.replace(False,0)
df = df.replace(True,1)
df = df.replace('True',1)
df = df.replace('0',0)
df = df.replace(1,True)
df = df.replace(0,False)
df

,Amygdala (AAL) (R),Angular gyrus (AAL) (L),Angular gyrus (AAL) (R),Anterior cingulate and paracingulate gyri (AAL) (L),Anterior cingulate and paracingulate gyri (AAL) (R),Calcarine fissure and surrounding cortex (AAL) (L),Calcarine fissure and surrounding cortex (AAL) (R),Caudate nucleus (AAL) (L),Caudate nucleus (AAL) (R),Cerebellum_10 (AAL) (L),...,Thalamus (AAL) (L),Thalamus (AAL) (R),Vermis_10 (AAL),Vermis_1_2 (AAL),Vermis_3 (AAL),Vermis_4_5 (AAL),Vermis_6 (AAL),Vermis_7 (AAL),Vermis_8 (AAL),Vermis_9 (AAL)
0,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
1,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,True,True,True,True,True,True,True,True,True,...,False,False,True,False,True,True,True,False,False,False
3,False,True,True,True,True,True,True,True,True,True,...,False,True,True,False,True,True,True,True,True,True
4,False,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,True
5,False,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,False
6,False,True,True,True,True,True,True,True,True,True,...,False,False,True,True,True,True,True,True,False,False
7,False,True,True,True,True,True,True,False,True,True,...,False,False,True,False,False,True,True,False,False,False
8,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,False,False,False
9,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,True
10,False,True,True,True,True,True,True,True,True,True,...,False,False,True,True,True,True,True,True,True,True
11,False,True,True,True,True,True,True,True,True,True,...,False,False,True,False,False,True,True,False,False,False
12,False,True,True,True,True,True,True,False,True,True,...,False,False,True,True,True,True,True,True,False,False
13,False,True,True,False,True,True,True,False,True,True,...,False,False,True,False,False,False,True,True,False,False
14,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
15,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,False,True,True,False,False,True,True,False,False,True,...,False,False,True,True,True,True,True,False,False,False
17,False,True,True,True,True,True,True,True,True,True,...,False,False,True,True,True,True,True,True,True,True
18,False,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,False
19,False,True,True,True,True,True,True,False,True,True,...,True,True,True,False,True,True,True,True,False,False

In [10]:
dfb = apriori(df, min_support = 0.8, use_colnames = True,low_memory=True)
dfb
# dfb['length'] = dfb['itemsets'].apply(lambda x: len(x))
# dfb['itemsets'] = dfb['itemsets'].apply(lambda x: ",".join(x))
# dfb

:

:

In [ ]:
dfb['itemsets'].apply(lambda el: ",".join(el))
dfb.to_csv('associationMinus.csv') 
files.download('associationMinus.csv')

In [ ]:
# getting list containg name of area and a 2 dimensiona list - two arrays containg SUV related to this area first is for left second is right
tupleList= []
workingOddList = []
for i in range(rowNumber):
  
  if (i%2==0): # when is even
    workingOddList = frame[i,1:].astype('float64')
  else:
    title =  frame[i,0].replace(' (R)','')
    tupleList.append( (title, np.array([workingOddList,frame[i,1:].astype('float64') ]  )) )  # so first is left second is right

In [ ]:
dfLeft = pd.DataFrame(
    list(map(lambda  x:  x[1][0]  , tupleList.copy()))
                  )
dfRight = pd.DataFrame(
    list(map(lambda  x:  x[1][0]  , tupleList.copy()))
                  )
dFNames = pd.DataFrame(
    list(map(lambda  x:  x[0]  , tupleList.copy()))
                  )


from google.colab import files
dfLeft.transpose().to_csv('dfLeft.csv') 
files.download('dfLeft.csv')

dfRight.transpose().to_csv('dfRight.csv') 
files.download('dfRight.csv')

dFNames.transpose().to_csv('dFNames.csv') 
files.download('dFNames.csv')

In [ ]:
def myplot (tupleListt):
  # sorting from biggest to smallest
  sortt = sorted(tupleListt, key=itemgetter(1))


  print(sortt)
  #preparing names and values to plot
  plt.figure(figsize=(15, 15))
  plt.xticks(rotation=90)
  plot = plt.plot(*zip(*sortt), label )


import pandas as pd


def myplotWithErrorBars (tupleListt):
  # sorting from biggest to smallest
  sortt = sorted(tupleListt, key=itemgetter(1))
  #sorttmin = sorted(tupleListtMin, key=itemgetter(1))
  #sorttmax = sorted(tupleListMax, key=itemgetter(1))

  #preparing names and values to plot
  plt.figure(figsize=(15, 15))
  plt.xticks(rotation=90)
  xses  =list(map(lambda x: x[0], sortt.copy()))
  ys  =list(map(lambda x: x[1], sortt.copy()))
  ysmin = list(map(lambda x: x[2], sortt.copy()))
  ysmax = list(map(lambda x: x[3], sortt.copy()))
  #print(ysmin)
  #print(ysmax)
  #print(ys)
  df=pd.DataFrame({'x':xses, 'mean': ys, 'min': ysmin, 'max': ysmax })

  plt.plot( 'x', 'mean', data=df, marker='o', markerfacecolor='blue', markersize=12, color='skyblue', linewidth=4)
  plt.plot( 'x', 'min', data=df, marker='', color='olive', linewidth=2)
  plt.plot( 'x', 'max', data=df, marker='', color='olive', linewidth=2, linestyle='dashed', label="max")
  plt.legend()


 # plt.errorbar(xses, ys , xerr=0.2, yerr=0.4)

  #plot = plt.plot(*zip(*sortt), label = "mean")
  #plot = plt.plot(*zip(*sorttmin),label = "min")
  #plot = plt.plot(*zip(*sorttmax), label = "max")

In [ ]:
# plotting left to right 

from operator import itemgetter, attrgetter
def leftToRight  ():
  tupleListLoc = tupleList.copy()# to prevent mutating original array

  # here we have a name of roi and a list with element wise divisions ritht to left
  rToLeft = list(map(lambda x: (x[0], x[1][0].astype('float64')/ x[1][1].astype('float64')), tupleListLoc))
  # getting median of all values
  rToLeft =list(map(lambda x: (x[0],np.mean(x[1]),np.min(x[1]) ,np.max(x[1])), rToLeft.copy()))

  print(rToLeft)

  myplotWithErrorBars(rToLeft)

leftToRight ()

In [ ]:
#plot with standard deviations
def nextWePlotWithStandardDeviations () :
  from operator import itemgetter, attrgetter
  tupleListLoc = tupleList.copy()# to prevent mutating original array

  # here we have a name of roi and a list with element wise divisions ritht to left
  rToLeft = list(map(lambda x: (x[0], x[1][0].astype('float64')/ x[1][1].astype('float64')), tupleListLoc))
  # getting median of all values
  rToLeft =list(map(lambda x: (x[0],np.mean(x[1]),np.mean(x[1])- np.std(x[1]) ,np.mean(x[1])+ np.std(x[1])), rToLeft.copy()))


  myplotWithErrorBars(rToLeft)

nextWePlotWithStandardDeviations ()

In [ ]:
# plotting scatter plot of right to left

from operator import itemgetter, attrgetter
def leftToRightScatterPlot  ():
  tupleListLoc = tupleList.copy()# to prevent mutating original array

  # here we have a name of roi and a list with element wise divisions ritht to left
  rToLeft = list(map(lambda x: (x[0], x[1][0].astype('float64')/ x[1][1].astype('float64')), tupleListLoc))
  # getting median of all values
  #rToLeft =list(map(lambda x: (x[0],np.mean(x[1]),np.min(x[1]) ,np.max(x[1])), rToLeft.copy()))

  print(rToLeft)
  #sortt = sorted(rToLeft, key=itemgetter(1))
  rToLeft =list(map(lambda x: [x[0]]+ x[1] , rToLeft.copy()))
  df = pd.DataFrame(rToLeft)
  print(df)

  ax1 = df.plot.scatter(x= 1, y=1, c='DarkBlue')



leftToRightScatterPlot ()

In [ ]:
#checking weather we have normal distribution of our values
from scipy import stats
# we are getting a list of p values associated with each row - where each row represents values of roi related to this particular roi 
frameLoc = frame.copy()
def getShpiro (liist):
  res = stats.shapiro(liist[1:].astype('float64'))[1]
  if(res>0.05):
      print(liist[0])
  return  res

shapiro_testListOfP = list(map(lambda x: (x[0],  getShpiro (x)), frameLoc))
#ksTest =  list(map(lambda x: (x[0], stats.kstest(x[1:], 'norm')), frameLoc))

# sorting from biggest to smallest
sortt = sorted(shapiro_testListOfP, key=itemgetter(1))
#preparing names and values to plot
plt.figure(figsize=(25, 15))
plt.xticks(rotation=90)
plot = plt.plot(*zip(*sortt))

In [ ]:
# plotting spearman correlations values

from operator import itemgetter, attrgetter
def spearmanAllVal():
  tupleListLoc = tupleList.copy()# to prevent mutating original array
  # here we have a name of roi and a list with element wise divisions ritht to left
  spearmann = list(map(lambda x: (x[0], scipy.stats.spearmanr(x[1][0], x[1][1])[0]), tupleListLoc))

spearmanAllVal()

In [ ]:
# plotting spearman correlations p values

from operator import itemgetter, attrgetter
def spearmanCorrel (name,tupl) :
  res = scipy.stats.spearmanr(tupl[0].astype('float64'),tupl[1].astype('float64'))
  return  res[1]


def spearmanPVal():
  tupleListLoc = tupleList.copy()# to prevent mutating original array
  # here we have a name of roi and a list with element wise divisions ritht to left
  spearmann = np.array(list(map(lambda x:  spearmanCorrel(x[0],x[1]), tupleListLoc)))
  print
  print(' min ')  
  print( spearmann.min())
  print(' max ')  
  print( spearmann.max())
spearmanPVal()

In [ ]:
# checking kl divergence between left and right distributions
# import tensorflow as tf
import sklearn.metrics
from operator import itemgetter, attrgetter
def klDiv():

  # kl = tf.keras.losses.KLDivergence()
  tupleListLoc = tupleList.copy()# to prevent mutating original array
  klDiv = list(map(lambda x: (x[0], sklearn.metrics.mutual_info_score(x[1][0].astype('float64'), x[1][1].astype('float64'))), tupleListLoc))
  print(klDiv)
  myplot(klDiv)
klDiv()

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
def getConcatenatedValues (tupll) :
  return np.concatenate((tupll[1][0], tupll[1][1]), axis=None)
def plotCorrelationMatrix():
  tupleListUpper = tupleList.copy()# to prevent mutating original array
  # here we have a name of roi and a list with element wise divisions ritht to left
  matr ={}

  for i in range(np.array(tupleListUpper).shape[0]):
    corrToCompare = tupleListUpper[i]
  
    matr[corrToCompare[0]] = corrToCompare[1][1]
    #getConcatenatedValues(corrToCompare)
  return matr
# np.array(plotCorrelationMatrix()).shape
matr = plotCorrelationMatrix()


corr= pd.DataFrame(matr).corr(method='spearman')

def CorrMtx(df, dropDuplicates = True):

    # Your dataset is already a correlation matrix.
    # If you have a dateset where you need to include the calculation
    # of a correlation matrix, just uncomment the line below:
    # df = df.corr()

    # Exclude duplicate correlations by masking uper right values
    if dropDuplicates:    
        mask = np.zeros_like(df, dtype=np.bool)
        mask[np.triu_indices_from(mask)] = True

    # Set background color / chart style
    sns.set_style(style = 'white')

    # Set up  matplotlib figure
    f, ax = plt.subplots(figsize=(11, 9))

    # Add diverging colormap from red to blue
    cmap = sns.diverging_palette(250, 10, as_cmap=True)

    # Draw correlation plot with or without duplicates
    if dropDuplicates:
        sns.heatmap(df, mask=mask, cmap=cmap, 
                square=True,
                linewidth=.5, cbar_kws={"shrink": .5}, ax=ax)
    else:
        sns.heatmap(df, cmap=cmap, 
                square=True,
                linewidth=.5, cbar_kws={"shrink": .5}, ax=ax)
        
CorrMtx(corr)        
#sns.heatmap(new_df, annot = True)

# sns.heatmap(new_df, 
#             xticklabels=new_df.columns.values,
#             yticklabels=new_df.columns.values)
#sns.heatmap(plotCorrelationMatrix())

In [ ]:
# #Checking p values of spearman correlations 

from scipy.stats import spearmanr

matr= pd.DataFrame(plotCorrelationMatrix())
rho= pd.DataFrame(matr).corr(method='spearman')
pval = matr.corr(method=lambda x, y: spearmanr(x, y)[1]) - np.eye(*rho.shape)
#p = pval.applymap(lambda x: ''.join(['*' for t in [0.01,0.05,0.1] if x<=t]))
pp = rho.round(2).astype(str) + p
CorrMtx(pval)

In [ ]:
## getting strongest and weakest correlations
def getStrongestAndWeakestCorrelations():
  tupleListUpper = tupleList.copy()# to prevent mutating original array
  # here we have a name of roi and a list with element wise divisions ritht to left
  resList =[]
  print(np.array(matr).shape )
  for i in range(np.array(tupleListUpper).shape[0]):
    corrToCompare = tupleListUpper[i] 
    tupleListLoc = tupleList.copy()
    spearmanLoc = list(map(lambda x:  scipy.stats.spearmanr(getConcatenatedValues(corrToCompare),getConcatenatedValues(x))[0], tupleListLoc))
    resList+=spearmanLoc
  return resList

sortt = sorted(getStrongestAndWeakestCorrelations())
print(sortt[5:])
print(sortt[:5])

# Scatter plosts

In [ ]:
# creating scatterplot

worksheet= spreadsheet.worksheet('left_to_right') ;

# get_all_values gives a list of rows.
rows = worksheet.get('A1:U54')
df = pd.DataFrame(rows)
# headers = df.iloc[0]
# new_df  = pd.DataFrame(df.values[1:], columns=headers)

# cols = list(df.columns) 

# prepare the data
df = df.melt(id_vars=df.columns[0])
df = df.drop(labels=['variable'], axis=1)
df.columns = ['variable', 'value']
#df = df.sort_values(by='variable')
df = df.sort_values([ 'value', 'variable'],ascending = False)
df = df.reset_index(drop=True)


# plot the data
fig = px.strip(df, x='variable', y='value', color='value', stripmode='overlay')

fig.update_layout(plot_bgcolor='white',
                  paper_bgcolor='white',
                  showlegend=False,
                  xaxis=dict(title=None, linecolor='gray', mirror=True),
                  yaxis=dict(title=None, linecolor='gray', mirror=True)
                  ,height = 1200)

fig.update_xaxes(type='category')
fig.update_yaxes(zeroline=True,showgrid = True)

fig.show()

# Analyzing standard deviations from template

In [ ]:
worksheet= spreadsheet.worksheet('mean_podsumowania') ;
rows = worksheet.get('A1:U117')
frame = np.array(rows)[1:,:] # ignoring first row
df= pd.DataFrame(frame)
df['mean'] = df.mean(axis=1)
df